workspace = { members = ["crates/obsidian_ui"] }
[package]
name = "bevy_reactor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# anyhow = "1.0.79"
bevy = "0.13.0"
bevy_color = { path = "../bevy_color" }
# bevy = { git = "https://github.com/bevyengine/bevy.git", features = [
#   "dynamic_linking",
# ], branch = "main" }
bevy_mod_picking = "0.18.0"
impl-trait-for-tuples = "0.2.2"
# ron = "0.8.1"
# serde = "1.0.196"
# thiserror = "1.0.57"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
obsidian_ui = { path = "crates/obsidian_ui" }

# [patch.crates-io]
# bevy = { git = "https://github.com/bevyengine/bevy.git", features = [
#   "dynamic_linking",
# ], branch = "main" }
