[package]
name = "bevy_reactor_view"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {workspace=true}
bevy_reactor_core = {path ="../bevy_reactor_core"}
bevy_reactor_style = {path ="../bevy_reactor_style"}
impl-trait-for-tuples = "0.2.2"
smallvec = "1.13.2"